namespace:
  create: true

gatewayClass:
  create: true
  name: traefik

gateway:
  enabled: true
  name: traefik-gateway
  listeners:
    - name: web
      protocol: HTTP
      port: 80
      allowedRoutesFrom: All

exampleRoute:
  enabled: false

traefik:
  deployment:
    replicas: 2

  nodeSelector:
    cloud.google.com/gke-nodepool: core_nodes

  tolerations:
    - key: dedicated
      operator: Equal
      value: core
      effect: NoSchedule

  affinity: {}

  service:
    type: ClusterIP
