{{- if and .Values.edgeGateway.enabled .Values.edgeGateway.healthCheckPolicy.enabled }}
{{- $svcNs := include "traefik-gatewayapi.traefikServiceNamespace" . -}}
{{- $svcName := include "traefik-gatewayapi.traefikServiceName" . -}}
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: {{ .Values.edgeGateway.healthCheckPolicy.name }}
  namespace: {{ $svcNs }}
spec:
  default:
    checkIntervalSec: {{ .Values.edgeGateway.healthCheckPolicy.checkIntervalSec }}
    timeoutSec: {{ .Values.edgeGateway.healthCheckPolicy.timeoutSec }}
    healthyThreshold: {{ .Values.edgeGateway.healthCheckPolicy.healthyThreshold }}
    unhealthyThreshold: {{ .Values.edgeGateway.healthCheckPolicy.unhealthyThreshold }}
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: {{ .Values.edgeGateway.healthCheckPolicy.requestPath }}
        portSpecification: {{ .Values.edgeGateway.healthCheckPolicy.portSpecification }}
{{- if eq .Values.edgeGateway.healthCheckPolicy.portSpecification "USE_FIXED_PORT" }}
        port: {{ .Values.edgeGateway.healthCheckPolicy.port }}
{{- end }}
  targetRef:
    group: ""
    kind: Service
    name: {{ $svcName }}
{{- end }}
