{{- if .Values.edgeGateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.edgeGateway.name }}
  namespace: {{ .Values.edgeGateway.namespace }}
spec:
  gatewayClassName: {{ .Values.edgeGateway.className }}
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ .Values.edgeGateway.tls.secretName }}
      allowedRoutes:
        namespaces:
          from: All
{{- end }}
