{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "traefik-gatewayapi.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  gatewayClassName: {{ .Values.gatewayClass.name }}
  listeners:
{{- range .Values.gateway.listeners }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      allowedRoutes:
        namespaces:
          from: {{ .allowedRoutesFrom | default "All" }}
{{- end }}
{{- end }}
